name: eds

services:
  app:
    container_name: eds_svc
    build:
      context: ..
      dockerfile: docker/.dockerfile
    image: eds_svc_image:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/eds_staging
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: eds_db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eds_staging
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./config:/etc/mysql/conf.d # Where MySQL looks for config scripts.
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql # Where MySQL looks for init scripts.
      - eds_volume:/var/lib/mysql # Uses named volume for persisting MySQL data.
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eds_volume:
    name: eds_db_data
